# #####################################################################
# Automatically generated by qmake (2.01a) mar sep 15 16:55:43 2009
# #####################################################################
TEMPLATE = app
TARGET = app
QT += core \
    gui

# Input
HEADERS += src/script/ScriptBuilder.h \
    src/gui/PreprocessingScriptParametersForm.h \
    src/mfa/MultifractalAnalysis.h \
    src/utils/MatrixOperations.h \
    src/cra/CorrelationAnalysis.h \
    src/gui/CorrelationAnalysisParametersForm.h \
    src/gui/CorrelationAnalysisResultsForm.h \
    src/gui/MfaResultsController.h \
    src/mfa/MultifractalAnalyzer.h \
    src/mfa/Plotter.h \
    src/utils/Linear.h \
    src/mfa/SandBoxMethod.h \
    src/utils/SeqLoader.h \
    src/gui/CgrResultsForm.h \
    src/gui/ImageViewer.h \
    src/gui/SequenceListModel.h \
    src/utils/Matrix.h \
    src/cgr/ChaosGameRepresentation.h \
    src/utils/Definitions.h \
    src/utils/CustomSequencesContainer.h \
    src/gui/TreeModel.h \
    src/gui/TreeItem.h \
    src/app/AppController.h \
    src/gui/CgrParametersForm.h \
    src/gui/MainWindow.h \
    src/gui/MfaParametersForm.h \
    src/gui/MfaResultsForm.h \
    src/utils/Utils.h
SOURCES += src/script/ScriptBuilder.cpp \
    src/gui/PreprocessingScriptParametersForm.cpp \
    src/mfa/MultifractalAnalysis.cpp \
    src/utils/MatrixOperations.cpp \
    src/cra/CorrelationAnalysis.cpp \
    src/gui/CorrelationAnalysisParametersForm.cpp \
    src/gui/CorrelationAnalysisResultsForm.cpp \
    src/gui/MfaResultsController.cpp \
    src/mfa/MultifractalAnalyzer.cpp \
    src/mfa/Plotter.cpp \
    src/mfa/SandBoxMethod.cpp \
    src/utils/SeqLoader.cpp \
    src/gui/CgrResultsForm.cpp \
    src/gui/ImageViewer.cpp \
    src/gui/SequenceListModel.cpp \
    src/cgr/ChaosGameRepresentation.cpp \
    src/utils/CustomSequencesContainer.cpp \
    src/gui/TreeModel.cpp \
    src/gui/TreeItem.cpp \
    src/app/AppController.cpp \
    src/app/main.cpp \
    src/gui/CgrParametersForm.cpp \
    src/gui/MainWindow.cpp \
    src/gui/MfaParametersForm.cpp \
    src/gui/MfaResultsForm.cpp
FORMS += src/gui/PreprocessingScriptParametersForm.ui \
    src/gui/CorrelationAnalysisParametersForm.ui \
    src/gui/CorrelationAnalysisResultsForm.ui \
    src/gui/CgrResultsForm.ui \
    src/gui/ImageViewer.ui \
    src/gui/CgrParametersForm.ui \
    src/gui/MainWindow.ui \
    src/gui/MfaParametersForm.ui \
    src/gui/MfaResultsForm.ui
DEPENDPATH += . \
    src/ \
    src/app \
    src/cgr \
    src/gui \
    src/utils
INCLUDEPATH += . \
    src/ \
    src/app \
    src/cgr \
    src/utils \
    src/gui
INCLUDEPATH += /usr/include \
    /usr/local/include
LIBS += -L/usr/local/lib \
    -lbpp-utils \
    -lbpp-seq \
    -lbpp-numcalc \
    -lbpp-qt \
    -lbpp-raa

# -lbpp-phyl \
LIBS += -L/usr/lib \
    -lmgl \
    -lmgl-qt

# -L/opt/bpp/lib \
# -lbpp-utils \
# -lbpp-seq \
# -lbpp-numcalc \
# -lbpp-phyl \
RESOURCES += resources/resources.qrc
