#! /bin/sh
make clean
pwd
rm -fr debug/*.*
rm app
rm tmp/*
rm bin/*
rm release/*
rm doc/**/*.*
cd test/MatrixOperations
make clean
rm -fr test
cd ../../
tar -zcvf ../GenomAMf_entrega_$1.tgz ../GenomAMf_entrega
mv ../GenomAMf_entrega_$1.tgz $2/Univalle/Trabajo\ de\ Grado/Fuente
sync
